/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistapantalla;

import java.util.logging.Level;
import java.util.logging.Logger;
import modelotablas.TableModelProducto;
import vistabd.Modelo;

/**
 *
 * @author Paco Aldarias <paco.aldarias@ceedcv.es>
 */
public class VistaProducto extends javax.swing.JDialog {

  private Modelo modelo;
  private TableModelProducto tablemodelproducto;

  /**
   * Creates new form VistaCliente
   */
  public VistaProducto() throws Exception {
    initComponents();
  }

  public VistaProducto(Modelo modelo_)
          throws Exception {
    modelo = modelo_;
    tablemodelproducto = new TableModelProducto(modelo);
    initComponents();

  }

  public VistaProducto(java.awt.Frame vista, boolean b, Modelo modelo_)
          throws Exception {
    super(vista, b);
    modelo = modelo_;
    tablemodelproducto = new TableModelProducto(modelo);
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize
   * the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1Producto = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    VistaProductoAnadir = new javax.swing.JButton();
    VistaProductoBorrar = new javax.swing.JButton();
    VistaProductoSalir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(166, 39, 201));

    jTable1Producto.setBackground(new java.awt.Color(34, 253, 226));
    jTable1Producto.setModel(tablemodelproducto);
    jScrollPane1.setViewportView(jTable1Producto);

    jLabel1.setText("PRODUCTOS");

    VistaProductoAnadir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-mas-icono-5518-48.png"))); // NOI18N
    VistaProductoAnadir.setText("Añadir");
    VistaProductoAnadir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    VistaProductoAnadir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    VistaProductoAnadir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VistaProductoAnadirActionPerformed(evt);
      }
    });

    VistaProductoBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-borrar-la-salida-icono-8537-48.png"))); // NOI18N
    VistaProductoBorrar.setText("Borrar");
    VistaProductoBorrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    VistaProductoBorrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    VistaProductoBorrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VistaProductoBorrarActionPerformed(evt);
      }
    });

    VistaProductoSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir-de-mi-perfil-icono-3964-128.png"))); // NOI18N
    VistaProductoSalir.setText("Salir");
    VistaProductoSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    VistaProductoSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    VistaProductoSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        VistaProductoSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(201, 201, 201)
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(41, 41, 41)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(VistaProductoAnadir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(VistaProductoBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(VistaProductoSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
        .addContainerGap(63, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(27, 27, 27)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(VistaProductoAnadir)
          .addComponent(VistaProductoBorrar)
          .addComponent(VistaProductoSalir))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void VistaProductoAnadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProductoAnadirActionPerformed
  }//GEN-LAST:event_VistaProductoAnadirActionPerformed

  private void VistaProductoSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProductoSalirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_VistaProductoSalirActionPerformed

  private void VistaProductoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaProductoBorrarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_VistaProductoBorrarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          new VistaProducto().setVisible(true);
        } catch (Exception ex) {
          Logger.getLogger(VistaProducto.class.getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton VistaProductoAnadir;
  private javax.swing.JButton VistaProductoBorrar;
  private javax.swing.JButton VistaProductoSalir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTable1Producto;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the VistaProducto1Anadir
   */
  public javax.swing.JButton getVistaProductoAnadir() {
    return VistaProductoAnadir;
  }

  /**
   * @return the VistaProducto1Borrar
   */
  public javax.swing.JButton getVistaProductoBorrar() {
    return VistaProductoBorrar;
  }

  /**
   * @return the VistaProducto1Salir
   */
  public javax.swing.JButton getVistaProductoSalir() {
    return VistaProductoSalir;
  }

  /**
   * @return the jTable1Producto
   */
  public javax.swing.JTable getjTable1Producto() {
    return jTable1Producto;
  }

  public void setModelo(Modelo modelo_) {
    modelo = modelo_;
  }
}
