/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistapantalla;

import javax.swing.JOptionPane;
import util.Constantes;

/**
 *
 * @author Paco Aldarias <paco.aldarias@ceedcv.es>
 */
public class VistaLogin extends javax.swing.JDialog {

  private VistaPrincipal vista;
  private String user;
  private String pass;
  private boolean acceso;
  private String title;

  public VistaLogin(java.awt.Frame parent, boolean modal) {

    super(parent, modal);
    initComponents();
    this.setLocation(630, 132);
    //Constantes c = new Constantes();
    //this.setTitle(c.NOMAPLI);
  }

  /**
   * This method is called from within the constructor to initialize
   * the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    JTextFieldUsuario = new javax.swing.JTextField();
    vistaLoginEntrar = new javax.swing.JButton();
    JPasswordFieldPassword = new javax.swing.JPasswordField();
    vistaLoginSalir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(10, 246, 149));
    jPanel1.setForeground(new java.awt.Color(70, 208, 215));

    jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(247, 237, 237));
    jLabel1.setText("Control de Acceso");

    jLabel2.setForeground(new java.awt.Color(238, 253, 236));
    jLabel2.setText("Usuario:");

    jLabel3.setForeground(new java.awt.Color(248, 236, 236));
    jLabel3.setText("Contraseña:");

    JTextFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JTextFieldUsuarioActionPerformed(evt);
      }
    });

    vistaLoginEntrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Tick (1).png"))); // NOI18N
    vistaLoginEntrar.setText("Entrar");
    vistaLoginEntrar.setBorderPainted(false);
    vistaLoginEntrar.setContentAreaFilled(false);
    vistaLoginEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    vistaLoginEntrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    vistaLoginEntrar.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        vistaLoginEntrarMouseClicked(evt);
      }
    });
    vistaLoginEntrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        vistaLoginEntrarActionPerformed(evt);
      }
    });

    JPasswordFieldPassword.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        JPasswordFieldPasswordActionPerformed(evt);
      }
    });

    vistaLoginSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir-de-mi-perfil-icono-3964-128.png"))); // NOI18N
    vistaLoginSalir.setText("Salir");
    vistaLoginSalir.setBorderPainted(false);
    vistaLoginSalir.setContentAreaFilled(false);
    vistaLoginSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    vistaLoginSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    vistaLoginSalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        vistaLoginSalirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(61, 61, 61)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(vistaLoginSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(vistaLoginEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(54, 54, 54))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(117, 117, 117)
            .addComponent(jLabel1)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(54, 54, 54)
                .addComponent(JPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(121, 121, 121))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(30, 30, 30)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(JTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel2))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
              .addComponent(JPasswordFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jLabel3))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(vistaLoginEntrar))
          .addComponent(vistaLoginSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(43, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void vistaLoginSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaLoginSalirActionPerformed
    // TODO add your handling code here:
    //System.exit(0);
  }//GEN-LAST:event_vistaLoginSalirActionPerformed

  private void JPasswordFieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPasswordFieldPasswordActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JPasswordFieldPasswordActionPerformed

  private void vistaLoginEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vistaLoginEntrarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_vistaLoginEntrarActionPerformed

  private void vistaLoginEntrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaLoginEntrarMouseClicked
    // TODO add your handling code here:
  }//GEN-LAST:event_vistaLoginEntrarMouseClicked

  private void JTextFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextFieldUsuarioActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_JTextFieldUsuarioActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        VistaLogin dialog = new VistaLogin(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
          @Override
          public void windowClosing(java.awt.event.WindowEvent e) {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPasswordField JPasswordFieldPassword;
  private javax.swing.JTextField JTextFieldUsuario;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel1;
  public javax.swing.JButton vistaLoginEntrar;
  private javax.swing.JButton vistaLoginSalir;
  // End of variables declaration//GEN-END:variables

  /**
   * @param user the user to set
   */
  public void setUser(String user) {
    this.user = user;
  }

  public String getUser() {
    return getJTextFieldUsuario().getText();
  }

  public String getPassword() {
    return getJPasswordFieldPassword().getText();
  }

  /**
   * @param pass the pass to set
   */
  public void setPass(String pass) {
    this.pass = pass;
  }

  public boolean getAcceso() {
    return isAcceso();
  }

  /**
   * @return the vista
   */
  public VistaPrincipal getVista() {
    return vista;
  }

  /**
   * @param vista the vista to set
   */
  public void setVista(VistaPrincipal vista) {
    this.vista = vista;
  }

  /**
   * @return the pass
   */
  public String getPass() {
    return pass;
  }

  /**
   * @return the acceso
   */
  public boolean isAcceso() {
    return acceso;
  }

  /**
   * @param acceso the acceso to set
   */
  public void setAcceso(boolean acceso) {
    this.acceso = acceso;
  }

  /**
   * @return the title
   */
  public String getTitle() {
    return title;
  }

  /**
   * @param title the title to set
   */
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * @return the JPasswordFieldPassword
   */
  public javax.swing.JPasswordField getJPasswordFieldPassword() {
    return JPasswordFieldPassword;
  }

  /**
   * @param JPasswordFieldPassword the JPasswordFieldPassword to set
   */
  public void setJPasswordFieldPassword(javax.swing.JPasswordField JPasswordFieldPassword) {
    this.JPasswordFieldPassword = JPasswordFieldPassword;
  }

  /**
   * @return the JTextFieldUsuario
   */
  public javax.swing.JTextField getJTextFieldUsuario() {
    return JTextFieldUsuario;
  }

  /**
   * @param JTextFieldUsuario the JTextFieldUsuario to set
   */
  public void setJTextFieldUsuario(javax.swing.JTextField JTextFieldUsuario) {
    this.JTextFieldUsuario = JTextFieldUsuario;
  }

  /**
   * @return the jLabel1
   */
  public javax.swing.JLabel getjLabel1() {
    return jLabel1;
  }

  /**
   * @param jLabel1 the jLabel1 to set
   */
  public void setjLabel1(javax.swing.JLabel jLabel1) {
    this.jLabel1 = jLabel1;
  }

  /**
   * @return the jLabel2
   */
  public javax.swing.JLabel getjLabel2() {
    return jLabel2;
  }

  /**
   * @param jLabel2 the jLabel2 to set
   */
  public void setjLabel2(javax.swing.JLabel jLabel2) {
    this.jLabel2 = jLabel2;
  }

  /**
   * @return the jLabel3
   */
  public javax.swing.JLabel getjLabel3() {
    return jLabel3;
  }

  /**
   * @param jLabel3 the jLabel3 to set
   */
  public void setjLabel3(javax.swing.JLabel jLabel3) {
    this.jLabel3 = jLabel3;
  }

  /**
   * @return the jPanel1
   */
  public javax.swing.JPanel getjPanel1() {
    return jPanel1;
  }

  /**
   * @param jPanel1 the jPanel1 to set
   */
  public void setjPanel1(javax.swing.JPanel jPanel1) {
    this.jPanel1 = jPanel1;
  }

  /**
   * @return the vistaLoginEntrar
   */
  public javax.swing.JButton getVistaLoginEntrar() {
    return vistaLoginEntrar;
  }

  /**
   * @param vistaLoginEntrar the vistaLoginEntrar to set
   */
  public void setVistaLoginEntrar(javax.swing.JButton vistaLoginEntrar) {
    this.vistaLoginEntrar = vistaLoginEntrar;
  }

  /**
   * @return the vistaLoginSalir
   */
  public javax.swing.JButton getVistaLoginSalir() {
    return vistaLoginSalir;
  }

  /**
   * @param vistaLoginSalir the vistaLoginSalir to set
   */
  public void setVistaLoginSalir(javax.swing.JButton vistaLoginSalir) {
    this.vistaLoginSalir = vistaLoginSalir;
  }
}
