/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistapantalla;

import javax.swing.JButton;

/**
 *
 * @author Paco Aldarias <paco.aldarias@ceedcv.es>
 */
public class VistaPrincipal extends javax.swing.JFrame {

  //private VistaLogin logi = new VistaLogin(this, true);
  /**
   * Creates new form VistaPrincipal
   */
  public VistaPrincipal() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize
   * the form. WARNING: Do NOT modify this code. The content of this
   * method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    Tienda = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    botonsalir = new javax.swing.JButton();
    botonConfigurar = new javax.swing.JButton();
    botonDocumentacion = new javax.swing.JButton();
    botonJavadoc = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    botonpedidos = new javax.swing.JButton();
    botonidentificacion = new javax.swing.JButton();
    botonclientes = new javax.swing.JButton();
    botonproductos = new javax.swing.JButton();
    jButton1 = new javax.swing.JButton();
    jPanel4 = new javax.swing.JPanel();
    jLabel1Fuente = new javax.swing.JLabel();
    jLabel1Autores = new javax.swing.JLabel();
    jLabel2Proyecto = new javax.swing.JLabel();
    jLabel3Fecha = new javax.swing.JLabel();
    jLabel1NombreAplicacion = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("TIENDA");

    jPanel1.setBackground(new java.awt.Color(227, 233, 241));

    Tienda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carrito.jpg"))); // NOI18N
    Tienda.setBorderPainted(false);
    Tienda.setContentAreaFilled(false);
    Tienda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    Tienda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jPanel3.setBackground(new java.awt.Color(53, 217, 161));
    jPanel3.setForeground(new java.awt.Color(12, 201, 123));

    botonsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir-de-gnome-icono-7637-64.png"))); // NOI18N
    botonsalir.setText("Salir");
    botonsalir.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    botonsalir.setBorderPainted(false);
    botonsalir.setContentAreaFilled(false);
    botonsalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonsalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonsalir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonsalirActionPerformed(evt);
      }
    });

    botonConfigurar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/chatroulette-admin.png"))); // NOI18N
    botonConfigurar.setText("Configurar");
    botonConfigurar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    botonConfigurar.setBorderPainted(false);
    botonConfigurar.setContentAreaFilled(false);
    botonConfigurar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonConfigurar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonConfigurar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonConfigurarActionPerformed(evt);
      }
    });

    botonDocumentacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/informacion-icono-7843-48.png"))); // NOI18N
    botonDocumentacion.setText("Documentación");
    botonDocumentacion.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    botonDocumentacion.setBorderPainted(false);
    botonDocumentacion.setContentAreaFilled(false);
    botonDocumentacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonDocumentacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonDocumentacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonDocumentacionActionPerformed(evt);
      }
    });

    botonJavadoc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/acoso-laboral-interrogacion.gif"))); // NOI18N
    botonJavadoc.setText("Javadoc");
    botonJavadoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    botonJavadoc.setBorderPainted(false);
    botonJavadoc.setContentAreaFilled(false);
    botonJavadoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonJavadoc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonJavadoc.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonJavadocActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(botonsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
        .addComponent(botonJavadoc, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(botonConfigurar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel3Layout.createSequentialGroup()
          .addGap(154, 154, 154)
          .addComponent(botonDocumentacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addContainerGap(309, Short.MAX_VALUE)))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(botonConfigurar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(botonJavadoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(botonsalir, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
        .addContainerGap())
      .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(botonDocumentacion, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
    );

    jPanel2.setBackground(new java.awt.Color(106, 231, 138));
    jPanel2.setBorder(null);
    jPanel2.setForeground(new java.awt.Color(28, 231, 40));

    botonpedidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuenta-icono-6432-48.png"))); // NOI18N
    botonpedidos.setText("Pedidos");
    botonpedidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonpedidos.setBorderPainted(false);
    botonpedidos.setContentAreaFilled(false);
    botonpedidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonpedidos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonpedidos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonpedidosActionPerformed(evt);
      }
    });

    botonidentificacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clave-de-inicio-de-sesion-icono-6843-128.png"))); // NOI18N
    botonidentificacion.setText("Login");
    botonidentificacion.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonidentificacion.setBorderPainted(false);
    botonidentificacion.setContentAreaFilled(false);
    botonidentificacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonidentificacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonidentificacion.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonidentificacionActionPerformed(evt);
      }
    });

    botonclientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cada-proyecto-de-ley-de-derechos-de-usuario-icono-4202-64.png"))); // NOI18N
    botonclientes.setText("Clientes");
    botonclientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonclientes.setBorderPainted(false);
    botonclientes.setContentAreaFilled(false);
    botonclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonclientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonclientesActionPerformed(evt);
      }
    });

    botonproductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pantalla-de-monitor-de-ordenador-icono-9301-64.png"))); // NOI18N
    botonproductos.setText("Productos");
    botonproductos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
    botonproductos.setBorderPainted(false);
    botonproductos.setContentAreaFilled(false);
    botonproductos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    botonproductos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    botonproductos.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        botonproductosActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(botonclientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(botonpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(botonidentificacion))
            .addGap(0, 11, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
        .addComponent(botonpedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(botonproductos, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(botonclientes, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(botonidentificacion)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logocolor.jpg"))); // NOI18N
    jButton1.setText("Ceed");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jPanel4.setBackground(new java.awt.Color(138, 221, 208));

    jLabel1Fuente.setText("Fuente");

    jLabel1Autores.setText("Autores");

    jLabel2Proyecto.setText("Proyecto");

    jLabel3Fecha.setText("Fecha");

    jLabel1NombreAplicacion.setText("NombreAplicacion");

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1Fuente)
          .addComponent(jLabel1Autores)
          .addComponent(jLabel2Proyecto)
          .addComponent(jLabel3Fecha)
          .addComponent(jLabel1NombreAplicacion))
        .addContainerGap(318, Short.MAX_VALUE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1NombreAplicacion)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1Autores)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2Proyecto)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel3Fecha)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel1Fuente)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(50, 50, 50)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(0, 0, Short.MAX_VALUE)
        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(21, 21, 21)
            .addComponent(Tienda, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(20, 20, 20)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 12, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void botonsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonsalirActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonsalirActionPerformed

  private void botonConfigurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConfigurarActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonConfigurarActionPerformed

  private void botonpedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpedidosActionPerformed
    // TODO add your handling code here:
    //VistaCliente vc = new VistaCliente(this, true);
    //vc.setVisible(true);
  }//GEN-LAST:event_botonpedidosActionPerformed

  private void botonidentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonidentificacionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonidentificacionActionPerformed

  private void botonclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonclientesActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonclientesActionPerformed

  private void botonproductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonproductosActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonproductosActionPerformed

  private void botonDocumentacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDocumentacionActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonDocumentacionActionPerformed

  private void botonJavadocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonJavadocActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_botonJavadocActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new VistaPrincipal().setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton Tienda;
  public javax.swing.JButton botonConfigurar;
  public javax.swing.JButton botonDocumentacion;
  public javax.swing.JButton botonJavadoc;
  public javax.swing.JButton botonclientes;
  public javax.swing.JButton botonidentificacion;
  public javax.swing.JButton botonpedidos;
  public javax.swing.JButton botonproductos;
  public javax.swing.JButton botonsalir;
  private javax.swing.JButton jButton1;
  private javax.swing.JLabel jLabel1Autores;
  private javax.swing.JLabel jLabel1Fuente;
  private javax.swing.JLabel jLabel1NombreAplicacion;
  private javax.swing.JLabel jLabel2Proyecto;
  private javax.swing.JLabel jLabel3Fecha;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  // End of variables declaration//GEN-END:variables

  /**
   * @return the Tienda
   */
  public javax.swing.JButton getTienda() {
    return Tienda;
  }

  /**
   * @param Tienda the Tienda to set
   */
  public void setTienda(javax.swing.JButton Tienda) {
    this.Tienda = Tienda;
  }

  /**
   * @return the botonclientes
   */
  public javax.swing.JButton getBotonclientes() {
    return botonclientes;
  }

  /**
   * @param botonclientes the botonclientes to set
   */
  public void setBotonclientes(javax.swing.JButton botonclientes) {
    this.botonclientes = botonclientes;
  }

  /**
   * @return the botondocumentacion
   */
  public javax.swing.JButton getBotondocumentacion() {
    return botonDocumentacion;
  }

  /**
   * @param botondocumentacion the botondocumentacion to set
   */
  public void setBotondocumentacion(javax.swing.JButton botondocumentacion) {
    this.botonConfigurar = botondocumentacion;
  }

  /**
   * @return the botonidentificacion
   */
  public javax.swing.JButton getBotonidentificacion() {
    return botonidentificacion;
  }

  /**
   * @param botonidentificacion the botonidentificacion to set
   */
  public void setBotonidentificacion(javax.swing.JButton botonidentificacion) {
    this.botonidentificacion = botonidentificacion;
  }

  /**
   * @return the botonpedidos
   */
  public javax.swing.JButton getBotonpedidos() {
    return botonpedidos;
  }

  /**
   * @param botonpedidos the botonpedidos to set
   */
  public void setBotonpedidos(javax.swing.JButton botonpedidos) {
    this.botonpedidos = botonpedidos;
  }

  /**
   * @return the botonproductos
   */
  public javax.swing.JButton getBotonproductos() {
    return botonproductos;
  }

  /**
   * @param botonproductos the botonproductos to set
   */
  public void setBotonproductos(javax.swing.JButton botonproductos) {
    this.botonproductos = botonproductos;
  }

  /**
   * @return the botonsalir
   */
  public javax.swing.JButton getBotonsalir() {
    return botonsalir;
  }

  /**
   * @param botonsalir the botonsalir to set
   */
  public void setBotonsalir(javax.swing.JButton botonsalir) {
    this.botonsalir = botonsalir;
  }

  /**
   * @return the jButton1
   */
  public javax.swing.JButton getjButton1() {
    return jButton1;
  }

  /**
   * @param jButton1 the jButton1 to set
   */
  public void setjButton1(javax.swing.JButton jButton1) {
    this.jButton1 = jButton1;
  }

  /**
   * @return the jLabel1Autores
   */
  public javax.swing.JLabel getjLabel1Autores() {
    return jLabel1Autores;
  }

  /**
   * @param jLabel1Autores the jLabel1Autores to set
   */
  public void setjLabel1Autores(javax.swing.JLabel jLabel1Autores) {
    this.jLabel1Autores = jLabel1Autores;
  }

  /**
   * @return the jLabel1Fuente
   */
  public javax.swing.JLabel getjLabel1Fuente() {
    return jLabel1Fuente;
  }

  /**
   * @param jLabel1Fuente the jLabel1Fuente to set
   */
  public void setjLabel1Fuente(javax.swing.JLabel jLabel1Fuente) {
    this.jLabel1Fuente = jLabel1Fuente;
  }

  /**
   * @return the jLabel1NombreAplicacion
   */
  public javax.swing.JLabel getjLabel1NombreAplicacion() {
    return jLabel1NombreAplicacion;
  }

  /**
   * @param jLabel1NombreAplicacion the jLabel1NombreAplicacion to set
   */
  public void setjLabel1NombreAplicacion(javax.swing.JLabel jLabel1NombreAplicacion) {
    this.jLabel1NombreAplicacion = jLabel1NombreAplicacion;
  }

  /**
   * @return the jLabel2Proyecto
   */
  public javax.swing.JLabel getjLabel2Proyecto() {
    return jLabel2Proyecto;
  }

  /**
   * @param jLabel2Proyecto the jLabel2Proyecto to set
   */
  public void setjLabel2Proyecto(javax.swing.JLabel jLabel2Proyecto) {
    this.jLabel2Proyecto = jLabel2Proyecto;
  }

  /**
   * @return the jLabel3Fecha
   */
  public javax.swing.JLabel getjLabel3Fecha() {
    return jLabel3Fecha;
  }

  /**
   * @param jLabel3Fecha the jLabel3Fecha to set
   */
  public void setjLabel3Fecha(javax.swing.JLabel jLabel3Fecha) {
    this.jLabel3Fecha = jLabel3Fecha;
  }

  /**
   * @return the jPanel1
   */
  public javax.swing.JPanel getjPanel1() {
    return jPanel1;
  }

  /**
   * @param jPanel1 the jPanel1 to set
   */
  public void setjPanel1(javax.swing.JPanel jPanel1) {
    this.jPanel1 = jPanel1;
  }

  /**
   * @return the jPanel2
   */
  public javax.swing.JPanel getjPanel2() {
    return jPanel2;
  }

  /**
   * @param jPanel2 the jPanel2 to set
   */
  public void setjPanel2(javax.swing.JPanel jPanel2) {
    this.jPanel2 = jPanel2;
  }

  /**
   * @return the jPanel3
   */
  public javax.swing.JPanel getjPanel3() {
    return jPanel3;
  }

  /**
   * @param jPanel3 the jPanel3 to set
   */
  public void setjPanel3(javax.swing.JPanel jPanel3) {
    this.jPanel3 = jPanel3;
  }

  /**
   * @return the jPanel4
   */
  public javax.swing.JPanel getjPanel4() {
    return jPanel4;
  }

  /**
   * @param jPanel4 the jPanel4 to set
   */
  public void setjPanel4(javax.swing.JPanel jPanel4) {
    this.jPanel4 = jPanel4;
  }

  /**
   * @return the botonJavadoc
   */
  public javax.swing.JButton getBotonJavadoc() {
    return botonJavadoc;
  }

  public JButton getBotonConfigurar() {
    return botonConfigurar;
  }
}
