/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vistapantalla;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import modelodatos.*;
import modelotablas.TableModelLinea;
import modelotablas.TableModelPedido;
import vistabd.Bd;
import vistabd.Modelo;

/**
 *
 * @author Paco Aldarias <paco.aldarias@ceedcv.es>
 */
public class VistaPedido extends javax.swing.JDialog {

  private Modelo modelo;
  private Bd bd;
  private TableModelPedido tablemodelpedido = null;
  private TableModelLinea tablemodellinea = null;
  private Pedido pedidoSelected = null;
  private String idpedidoSelected = "";

  /**
   * Creates new form VistaCliente
   */
  public VistaPedido() throws Exception {
    initComponents();
  }

  public VistaPedido(Modelo modelo_) throws Exception {
    modelo = modelo_;
    this.tablemodelpedido = new TableModelPedido(modelo);
    this.tablemodellinea = new TableModelLinea(modelo, "");
    initComponents();
  }

  public VistaPedido(java.awt.Frame vista, boolean b, Modelo modelo_) throws Exception {
    super(vista, b);
    modelo = modelo_;
    this.tablemodelpedido = new TableModelPedido(modelo);
    this.tablemodellinea = new TableModelLinea(modelo, "");
    initComponents();

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jButton1AnadirLinea = new javax.swing.JButton();
    jButton2BorrarLinea = new javax.swing.JButton();
    jButton3Salir = new javax.swing.JButton();
    jPanel2 = new javax.swing.JPanel();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTable1Pedido = new javax.swing.JTable();
    jLabel1 = new javax.swing.JLabel();
    jButton1AnadirPedido = new javax.swing.JButton();
    jButton2BorrarPedido = new javax.swing.JButton();
    jPanel3 = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    jScrollPane2 = new javax.swing.JScrollPane();
    jTable2Linea = new javax.swing.JTable();
    jPanel4 = new javax.swing.JPanel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4Totalpedido = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(51, 123, 221));

    jButton1AnadirLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-mas-icono-5518-48.png"))); // NOI18N
    jButton1AnadirLinea.setText("Añadir Linea");
    jButton1AnadirLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1AnadirLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton1AnadirLinea.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1AnadirLineaActionPerformed(evt);
      }
    });

    jButton2BorrarLinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-borrar-la-salida-icono-8537-48.png"))); // NOI18N
    jButton2BorrarLinea.setText("Borrar Linea");
    jButton2BorrarLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2BorrarLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
    jButton2BorrarLinea.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2BorrarLineaActionPerformed(evt);
      }
    });

    jButton3Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir-de-mi-perfil-icono-3964-128.png"))); // NOI18N
    jButton3Salir.setText("Salir");
    jButton3Salir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton3Salir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jTable1Pedido.setBackground(new java.awt.Color(34, 253, 226));
    jTable1Pedido.setModel(tablemodelpedido);
    jScrollPane1.setViewportView(jTable1Pedido);

    jLabel1.setText("PEDIDO");

    jButton1AnadirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/anadir-mas-icono-5518-48.png"))); // NOI18N
    jButton1AnadirPedido.setText("Añadir Pedido");
    jButton1AnadirPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton1AnadirPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    jButton2BorrarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cerrar-borrar-la-salida-icono-8537-48.png"))); // NOI18N
    jButton2BorrarPedido.setText("Borrar Pedido");
    jButton2BorrarPedido.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
    jButton2BorrarPedido.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
    jPanel2.setLayout(jPanel2Layout);
    jPanel2Layout.setHorizontalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
          .addGroup(jPanel2Layout.createSequentialGroup()
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel1))
              .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1AnadirPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2BorrarPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(0, 104, Short.MAX_VALUE)))
        .addContainerGap())
    );
    jPanel2Layout.setVerticalGroup(
      jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel2Layout.createSequentialGroup()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1AnadirPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jButton2BorrarPedido, javax.swing.GroupLayout.Alignment.TRAILING)))
    );

    jLabel2.setText("LINEA PEDIDO");

    jTable2Linea.setModel(tablemodellinea);
    jScrollPane2.setViewportView(jTable2Linea);

    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
    jPanel3.setLayout(jPanel3Layout);
    jPanel3Layout.setHorizontalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addGap(166, 166, 166)
            .addComponent(jLabel2))
          .addGroup(jPanel3Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    jPanel3Layout.setVerticalGroup(
      jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel3Layout.createSequentialGroup()
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
        .addContainerGap())
    );

    jPanel4.setBackground(new java.awt.Color(19, 229, 243));
    jPanel4.setForeground(new java.awt.Color(21, 32, 33));

    jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
    jLabel3.setText("TOTAL PEDIDO:");

    jLabel4Totalpedido.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
    jLabel4Totalpedido.setText("0");
    jLabel4Totalpedido.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
    jPanel4.setLayout(jPanel4Layout);
    jPanel4Layout.setHorizontalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel3)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel4Totalpedido, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    jPanel4Layout.setVerticalGroup(
      jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel4Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jLabel4Totalpedido))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(0, 0, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(219, 219, 219))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(15, 15, 15)
            .addComponent(jButton1AnadirLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(jButton2BorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
              .addComponent(jButton3Salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(234, 234, 234))))
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGap(51, 51, 51)
        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGap(15, 15, 15)
        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jButton3Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(jButton1AnadirLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButton2BorrarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        .addGap(10, 10, 10))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButton1AnadirLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1AnadirLineaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton1AnadirLineaActionPerformed

  private void jButton2BorrarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2BorrarLineaActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_jButton2BorrarLineaActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;


        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(VistaPedido.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(VistaPedido.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(VistaPedido.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(VistaPedido.class
              .getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        try {
          new VistaPedido().setVisible(true);


        } catch (Exception ex) {
          Logger.getLogger(VistaPedido.class
                  .getName()).log(Level.SEVERE, null, ex);
        }
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1AnadirLinea;
  private javax.swing.JButton jButton1AnadirPedido;
  private javax.swing.JButton jButton2BorrarLinea;
  private javax.swing.JButton jButton2BorrarPedido;
  private javax.swing.JButton jButton3Salir;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4Totalpedido;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JPanel jPanel2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JScrollPane jScrollPane2;
  private javax.swing.JTable jTable1Pedido;
  private javax.swing.JTable jTable2Linea;
  // End of variables declaration//GEN-END:variables

  public JTable getJTable1Pedido() {
    return jTable1Pedido;
  }

  public JButton getVistaPedidoAnadir() {
    return jButton1AnadirPedido;
  }

  public JButton getVistaPedidoBorrar() {
    return jButton2BorrarPedido;
  }

  public JButton getVistaPedidoSalir() {
    return jButton3Salir;
  }

  public JButton getVistaLineaAnadir() {
    return jButton1AnadirLinea;
  }

  public JButton getVistaLineaBorrar() {
    return jButton2BorrarLinea;
  }

  public JTable getJTable2Linea() {
    return jTable2Linea;
  }

  public JLabel getjLabel4Totalpedido() {
    return jLabel4Totalpedido;
  }

  public Object getLineaClicked() {
    return jTable1Pedido;
  }

  public void setModelo(Modelo modelo_) {
    modelo = modelo_;
  }
}
