package modelodatos;
// Generated 07-may-2014 19:22:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String id;
     private String nombre;
     private String email;
     private Set pedidos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Cliente(String id, String nombre, String email, Set pedidos) {
       this.id = id;
       this.nombre = nombre;
       this.email = email;
       this.pedidos = pedidos;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getPedidos() {
        return this.pedidos;
    }
    
    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }




}


