package modelodatos;
// Generated 07-may-2014 19:22:12 by Hibernate Tools 3.2.1.GA



/**
 * Configura generated by hbm2java
 */
public class Configura  implements java.io.Serializable {


     private String id;
     private String nombreaplicacion;
     private String autor;
     private String basedatos;
     private String fuentedatos;
     private String fecha;

    public Configura() {
    }

    public Configura(String id, String nombreaplicacion, String autor, String basedatos, String fuentedatos, String fecha) {
       this.id = id;
       this.nombreaplicacion = nombreaplicacion;
       this.autor = autor;
       this.basedatos = basedatos;
       this.fuentedatos = fuentedatos;
       this.fecha = fecha;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNombreaplicacion() {
        return this.nombreaplicacion;
    }
    
    public void setNombreaplicacion(String nombreaplicacion) {
        this.nombreaplicacion = nombreaplicacion;
    }
    public String getAutor() {
        return this.autor;
    }
    
    public void setAutor(String autor) {
        this.autor = autor;
    }
    public String getBasedatos() {
        return this.basedatos;
    }
    
    public void setBasedatos(String basedatos) {
        this.basedatos = basedatos;
    }
    public String getFuentedatos() {
        return this.fuentedatos;
    }
    
    public void setFuentedatos(String fuentedatos) {
        this.fuentedatos = fuentedatos;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


