package modelodatos;
// Generated 07-may-2014 19:22:12 by Hibernate Tools 3.2.1.GA



/**
 * Linea generated by hbm2java
 */
public class Linea  implements java.io.Serializable {


     private String idlinea;
     private Producto producto;
     private Pedido pedido;
     private String importe;
     private String cantidad;
     private String fecha;

    public Linea() {
    }

	
    public Linea(String idlinea) {
        this.idlinea = idlinea;
    }
    public Linea(String idlinea, Producto producto, Pedido pedido, String importe, String cantidad, String fecha) {
       this.idlinea = idlinea;
       this.producto = producto;
       this.pedido = pedido;
       this.importe = importe;
       this.cantidad = cantidad;
       this.fecha = fecha;
    }
   
    public String getIdlinea() {
        return this.idlinea;
    }
    
    public void setIdlinea(String idlinea) {
        this.idlinea = idlinea;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Pedido getPedido() {
        return this.pedido;
    }
    
    public void setPedido(Pedido pedido) {
        this.pedido = pedido;
    }
    public String getImporte() {
        return this.importe;
    }
    
    public void setImporte(String importe) {
        this.importe = importe;
    }
    public String getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(String cantidad) {
        this.cantidad = cantidad;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }




}


