package modelodatos;
// Generated 07-may-2014 19:22:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pedido generated by hbm2java
 */
public class Pedido  implements java.io.Serializable {


     private String id;
     private Cliente cliente;
     private String fecha;
     private Set lineas = new HashSet(0);

    public Pedido() {
    }

	
    public Pedido(String id) {
        this.id = id;
    }
    public Pedido(String id, Cliente cliente, String fecha, Set lineas) {
       this.id = id;
       this.cliente = cliente;
       this.fecha = fecha;
       this.lineas = lineas;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public Set getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set lineas) {
        this.lineas = lineas;
    }




}


