package modelodatos;
// Generated 07-may-2014 19:22:12 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private String idproducto;
     private String nombre;
     private String precio;
     private Set lineas = new HashSet(0);

    public Producto() {
    }

	
    public Producto(String idproducto, String nombre, String precio) {
        this.idproducto = idproducto;
        this.nombre = nombre;
        this.precio = precio;
    }
    public Producto(String idproducto, String nombre, String precio, Set lineas) {
       this.idproducto = idproducto;
       this.nombre = nombre;
       this.precio = precio;
       this.lineas = lineas;
    }
   
    public String getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(String idproducto) {
        this.idproducto = idproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(String precio) {
        this.precio = precio;
    }
    public Set getLineas() {
        return this.lineas;
    }
    
    public void setLineas(Set lineas) {
        this.lineas = lineas;
    }




}


